### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by EU1KY** [NanoVNA-Saver/nanovna-saver#159]
Traceback (most recent call last):
  File "nanovna-saver\NanoVNASaver\NanoVNASaver.py", line 924, in loadSweepFile
    self.dataUpdated()
  File "nanovna-saver\NanoVNASaver\NanoVNASaver.py", line 755, in dataUpdated
    c.setData(self.data)
  File "nanovna-saver\NanoVNASaver\Chart.py", line 3810, in setData
    self.calculateGroupDelay()
  File "nanovna-saver\NanoVNASaver\Chart.py", line 3827, in calculateGroupDelay
    phase_change = unwrappedData[1] - unwrappedData[0]
IndexError: index 1 is out of bounds for axis 0 with size 1

**To Reproduce**

Open as sweep a .s1p file with only one point in it, e.g.:

```
# MHz S RI R 50
28.000000 0.0 0.0
```

**Comment by zarath** [comment]
See fix #161
