### ISSUE TITLE
Please add R+jX and |Z| graphs calculated from S21 with G3TXQ method

### ISSUE THREAD

**Issue by yo2naa** [NanoVNA-Saver/nanovna-saver#165]
**Is your feature request related to a problem? Please describe.**
Measuring high impedance with NanoVNA is not reliable. 

**Describe the solution you'd like**
A better method of measuring high impedance to insert the device to be measured between CH0 and CH1, and calculate the impedance using S21 magnitude and phase. This method is described by G3TXQ here http://www.karinya.net/g3txq/chokes/#measurement
The explanation and formulas are here http://www.karinya.net/g3txq/chokes/s21.pdf
![image](https://user-images.githubusercontent.com/57508001/75610641-a3e28f00-5b1b-11ea-958f-0a66e0a04b34.png)

I've measured a 9.8 k small THD resistor using S11 and also the G3TXQ method, the results are much better using G3TXQ method:
![image](https://user-images.githubusercontent.com/57508001/75610706-2c612f80-5b1c-11ea-8de9-9f36347b431d.png)

**Describe alternatives you've considered**
Manually copy S21 data into excel for various frequencies and do the graph in excel

Thank you.

**Comment by satfan52** [comment]
Good idea! What about measuring very low impedances with accurracy? Can the same technique be used with as much accurracy ?

**Comment by cozycactus** [comment]
Good suggestion!

**Comment by yo2naa** [comment]
Kind reminder, thanks!

**Comment by akinad3** [comment]
this would be great to measure common-mode chokes!

**Comment by no3m** [comment]
+1

**Comment by rjordans** [comment]
To measure very low impedances you'd probably want to have a shunt-through measurement.  You want to have the DUT cause a significant variation in the measured S21 with variation of the component values.  W0QE has a nice video about the different approaches and how they impact the accuracy: https://www.youtube.com/watch?v=1UbEz73FGCU

**Comment by rjordans** [comment]
I had some time to play with this and implemented both the R+jX and |Z| graphs.  Some quick tests with a few SMD resistors, capacitors, and a ferrite bead I had on my desk seem to confirm the correct operation.

**Comment by no3m** [comment]
> I had some time to play with this and implemented both the R+jX and |Z| graphs. Some quick tests with a few SMD resistors, capacitors, and a ferrite bead I had on my desk seem to confirm the correct operation.

Getting the following errors when sweep segments are > 1:

S21 R+jX series plot enabled:

Traceback (most recent call last):
  File "/home/eric/Public/Downloads/amateur/software/nanovna-saver-rjordans/nanovna-saver/NanoVNASaver/Charts/Frequency.py", line 416, in paintEvent
    self.drawValues(qp)
  File "/home/eric/Public/Downloads/amateur/software/nanovna-saver-rjordans/nanovna-saver/NanoVNASaver/Charts/RI.py", line 206, in drawValues
    max_real = max(8, math.ceil(max_real))
OverflowError: cannot convert float infinity to integer
Aborted (core dumped)

S21 |Z| series plot enabled:

Traceback (most recent call last):
  File "/home/eric/Public/Downloads/amateur/software/nanovna-saver-rjordans/nanovna-saver/NanoVNASaver/Charts/Frequency.py", line 416, in paintEvent
    self.drawValues(qp)
  File "/home/eric/Public/Downloads/amateur/software/nanovna-saver-rjordans/nanovna-saver/NanoVNASaver/Charts/MagnitudeZ.py", line 107, in drawValues
    maxValue = 10*math.ceil(maxValue/10)
OverflowError: cannot convert float infinity to integer
Aborted (core dumped)

**Comment by rjordans** [comment]
Hmm, I did test with multiple segments, that does work for me.  But looking at the error I think this may be something different.

My guess is that your calibration is better than mine and you have nothing connected between the two ports.  That would result in S21 going to 0 and the series calculation divides by S21.  This gives an infinite impedance which apparently is causing trouble in the plotting code when it tries to get the automatic vertical scale correctly.

I'll have a look and see how to correct for this, maybe some large fixed upper bound no reasonable impedance values will work though that feels a bit hacky.

**Comment by no3m** [comment]
The DUT during these failures was a Murata 5000 series (4.7mH) surface mount CM choke.  Respective ends of the CM choke tied together and in series with Ch0 and Ch1, ground pass-thru.

**Comment by rjordans** [comment]
Ok, I've added some code to catch the infinite values and not use them for the plotting.  Hopefully this fixes your issue?  It looks like my initial guess was indeed correct and that the plotting code didn't handle this case properly yet.

**Comment by no3m** [comment]
latest changes seem to work fine.

**Comment by yo2naa** [comment]
Many thanks for adding this nice feature, really appreciate the effort. 
I'm trying to run the NanoVNASaver.x64 (nanovna-saver.exe) on my Windows 10 Pro 64 but I'm getting some errors:

 File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "NanoVNASaver\NanoVNASaver.py", line 28, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "NanoVNASaver\Windows\__init__.py", line 2, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "NanoVNASaver\Windows\AnalysisWindow.py", line 23, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "NanoVNASaver\Analysis\__init__.py", line 1, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "NanoVNASaver\Analysis\Analysis.py", line 22, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "scipy\signal\__init__.py", line 302, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "scipy\signal\filter_design.py", line 16, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "scipy\optimize\__init__.py", line 421, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "scipy\optimize\_shgo.py", line 9, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "scipy\spatial\__init__.py", line 107, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.7\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "scipy\spatial\transform\__init__.py", line 19, in <module>
  File "rotation.pyx", line 5, in init scipy.spatial.transform.rotation
ModuleNotFoundError: No module named 'scipy.spatial.transform._rotation_groups'

**Comment by rjordans** [comment]
@yo2naa That looks like an independent problem from this feature.  Looking at the error messages I believe that there is some component of the scipy library of Python missing in the install.

**Comment by r2axz** [comment]
I wrote [this Python script](https://github.com/r2axz/vic) to calculate complex impedances in s11 shunt, s21 series, and s21 shunt through modes. Works OK with NanoVNA as well as with any other VNA that can export Touchstone files. You can probably get the formulas there or use it for testing purposes. I use the script mainly for HF baluns / chokes measurements, but the math to calculate the impedance is universal.

**Comment by yo2naa** [comment]
> 
> 
> @yo2naa That looks like an independent problem from this feature. Looking at the error messages I believe that there is some component of the scipy library of Python missing in the install.

Many thanks Roel for all the good work. A friend of mine nanaged to build the exe on my PC, and now I can use the new features. Would you be so kind to add them to the markes too?
![image](https://user-images.githubusercontent.com/57508001/113519108-dc606200-9592-11eb-9fca-6028415c1087.png)
Thank you so much!

**Comment by akinad3** [comment]
@rjordans 
Opened a PR for adding the markers, but initial tests with @yo2naa shows differences between marker readings and data on graph (for R+jX series for example):
https://github.com/NanoVNA-Saver/nanovna-saver/pull/384

**Comment by yo2naa** [comment]
I can confirm that the graph for S21 R+jX series is unfortunately not OK:
![image](https://user-images.githubusercontent.com/57508001/113522061-6f56c780-95a6-11eb-8aa0-f391d0cce5fb.png)
However, S21 |Z| series graph is perfect:
![image](https://user-images.githubusercontent.com/57508001/113522138-eab87900-95a6-11eb-8a09-832d385e7029.png)

The marker values added by akinad3 are OK, thank you:
![image](https://user-images.githubusercontent.com/57508001/113522198-3c610380-95a7-11eb-9a0f-773c9ca1be91.png)

**Comment by rjordans** [comment]
@akinad3 thanks for adding the markers!

Regarding the weirdness you see, is this also in the graph view or just in the marker values?  And what would be an easy way for me to reproduce that so that I can see if it's an easy fix somewhere?

**Comment by yo2naa** [comment]
There is only a minor issue with R scale low limit:
![image](https://user-images.githubusercontent.com/57508001/113836977-0e8de180-9796-11eb-814a-03e39e8dabf4.png)
I think is is caused by negative R from the calculations, due to S21 measurement errors. For example, S21 series R for 69.4 kHz is -0.272 Ohm. Of course this is wrong, but not due to software, but because of wrong S21 measurements. However, the lower limit on the graph is still odd, -3623 Ohm.
![image](https://user-images.githubusercontent.com/57508001/113837893-efdc1a80-9796-11eb-8bcd-0e1f976c7a5c.png)

Here is the s2p file:

[7 turn RG142 toroid choke S21.zip](https://github.com/NanoVNA-Saver/nanovna-saver/files/6270264/7.turn.RG142.toroid.choke.S21.zip)

**Comment by rjordans** [comment]
Ah, yes, this indeed looks like it comes from inaccuracies in the initial measurement.  I'm unsure though how to handle this nicely but at least the lower bound of the axis could be closer to the measured value.  Looking at your graphs, the plotted label looks a lot like it's related to the data on the other axis, this may simply be a case of the wrong value being printed at that location.

**Comment by rjordans** [comment]
Ok, I finally had a bit of time to look into the axis labeling.  It seems that this happens for any real/imaginary plot and was a simple typo to fix!

**Comment by rjordans** [comment]
Getting the negative real part printed correctly in the markers also looks like an easy fix. I've added a comment to the pull request on how to get that fixed

**Comment by yo2naa** [comment]
Thank you all, working fine now!
