### ISSUE TITLE
Unable to install on MacOS

### ISSUE THREAD

**Issue by tony1tf** [NanoVNA-Saver/nanovna-saver#312]
I think I installed NanoVNA-Saver on  MacOS Mojave 10.14. using the guide here

https://github.com/NanoVNA-Saver/nanovna-saver
to get the software running under MacPorts on my MacBook Air 

All apparently installed OK, but I get the following errors when I try and run the app.
It's all a bit outside my knowledge, I'm afraid - I have tried re-installing, but makes no difference:

`Macs-Air:MacPorts` Tony$ NanoVNASaver 
Traceback (most recent call last):
  File "/opt/local/bin/NanoVNASaver", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/bin/NanoVNASaver", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (scipy 1.5.2 (/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages), Requirement.parse('scipy<1.5'), {'NanoVNASaver'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/bin/NanoVNASaver", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    @_call_aside
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3244, in _call_aside
    f(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3273, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'scipy<1.5' distribution was not found and is required by NanoVNASaver ``

I'm sure the issue will be obvious to you experts, so please be kind and help me!

Tony

**Comment by tony1tf** [comment]
Update - I have managed to get it installed using Brew, by repeating the procedure which I thought I had already done.
Tony
