### ISSUE TITLE
Crashes when "Connect to device" (SAA-2N, "Hugen" ver.)

### ISSUE THREAD

**Issue by htduan** [NanoVNA-Saver/nanovna-saver#365]
The nanoVNA-saver (ver. 0.3.8, Windows executable) recognizes the VNA as "S-A-A-2", but crashes when I hit "Connect to device". The following error messages are given:

2021-01-02 00:01:44,866 - NanoVNASaver.Hardware.NanoVNA_V2 - ERROR - Timeout reading version registers
Traceback (most recent call last):
  File "NanoVNASaver\NanoVNASaver.py", line 516, in serialButtonClick
  File "NanoVNASaver\NanoVNASaver.py", line 538, in connect_device
  File "NanoVNASaver\Hardware\Hardware.py", line 88, in get_VNA
  File "NanoVNASaver\Hardware\NanoVNA_V2.py", line 67, in __init__
  File "NanoVNASaver\Hardware\VNA.py", line 62, in __init__
  File "NanoVNASaver\Hardware\NanoVNA_V2.py", line 97, in read_features
  File "NanoVNASaver\Version.py", line 60, in __ge__
  File "NanoVNASaver\Version.py", line 48, in __gt__
AttributeError: 'NoneType' object has no attribute 'data'

The VNA has firmware version "git-20201117-9659de4". The unit is a SAA-2N, and was produced by hugen.

I did however find a way to work around this issue: when the VNA is under "USB MODE", nanoVNA-saver would connect to it without any problem. If I were to use nanoVNA-saver, I'd launch nanoVNA-QT first and quit (this put the VNA under "USB MODE" even when nanoVNA-QT is terminated), and then nanoVNA-saver could connect to it.

NanoVNA-saver is quite powerful and easy to use (especially when dealing with cal standards), and I'd hope this issue could be solved. Thank you.

**

OS: Windows 7 Pro SP1
NanoVNA-saver version: 0.3.8, Windows executable
NanoVNA v2 firmware version: git-20201117-9659de4 (SAA-2N produced by hugen)

**Comment by htduan** [comment]
The issue has been resolved. Its cause might lie in my operating system. Now both 0.3.8 (x64) and 0.3.9 (x86) are working fine with SAA-2N. Thanks for the outstanding software!
