### ISSUE TITLE
Support for 201 sweep points for the NanoVNA-F V2 new firmware V0.2.0

### ISSUE THREAD

**Issue by alfagulf** [NanoVNA-Saver/nanovna-saver#371]
Firmware V0.2.0 for the NanoVNA-F V2 now support upto 201 sweep points.

The NanoVNA Saver V0.3.8 program throws an exception when the NanoVNA-F V2 with firmware V0.2.0 is set to a number of sweep points greater than the default 101.

```
2021-01-26 12:51:15,147 - NanoVNASaver.SweepWorker - ERROR - list assignment index out of range
Traceback (most recent call last):
  File "/home/sabah/Documents/Electronics/NanoVNA-F V2/nanovna-saver-master/NanoVNASaver/SweepWorker.py", line 80, in run
    self._run()
  File "/home/sabah/Documents/Electronics/NanoVNA-F V2/nanovna-saver-master/NanoVNASaver/SweepWorker.py", line 124, in _run
    self.updateData(freq, values11, values21, i)
  File "/home/sabah/Documents/Electronics/NanoVNA-F V2/nanovna-saver-master/NanoVNASaver/SweepWorker.py", line 178, in updateData
    self.data11[offset + i] = data11[i]
IndexError: list assignment index out of range
```
I thought I bring this to your attention, hoping you rectify this in your new release.

Thanks
Sabah

**Comment by haupte** [comment]
I still suffer from the same problem as alfagulf 3 years ago.

> Firmware V0.2.0 for the NanoVNA-F V2 now support upto 201 sweep points.
> 
> The NanoVNA Saver V0.3.8 program throws an exception when the NanoVNA-F V2 with firmware V0.2.0 is set to a number of sweep points greater than the default 101.
> 
> ```
> 2021-01-26 12:51:15,147 - NanoVNASaver.SweepWorker - ERROR - list assignment index out of range
> Traceback (most recent call last):
>   File "/home/sabah/Documents/Electronics/NanoVNA-F V2/nanovna-saver-master/NanoVNASaver/SweepWorker.py", line 80, in run
>     self._run()
>   File "/home/sabah/Documents/Electronics/NanoVNA-F V2/nanovna-saver-master/NanoVNASaver/SweepWorker.py", line 124, in _run
>     self.updateData(freq, values11, values21, i)
>   File "/home/sabah/Documents/Electronics/NanoVNA-F V2/nanovna-saver-master/NanoVNASaver/SweepWorker.py", line 178, in updateData
>     self.data11[offset + i] = data11[i]
> IndexError: list assignment index out of range
> ```
> 
> I thought I bring this to your attention, hoping you rectify this in your new release.
> 
> Thanks Sabah

I suffer from the same problem as alfagulf 3 years ago.

Wouldn't there be a solution to raise the maximum number of sweep point in vnasaver?

Tnx, Erich
