### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ManfredII** [NanoVNA-Saver/nanovna-saver#433]
System: Debian bullseye
1. Go to:
python3.9 nanovna-saver.py
Rescan -> Resuli in "Port" is "/dev/ttyACM0 (NanoVNA)"
That is already good!
3. Click on 'Connect to Device'
4. Traceback (most recent call last):
  File "/home/ju/nanovna/NanoVNASaver/Controls/SerialControl.py", line 73, in serialButtonClick
    self.connect_device()
  File "/home/ju/nanovna/NanoVNASaver/Controls/SerialControl.py", line 93, in connect_device
    self.app.vna = get_VNA(self.interface)
  File "/home/ju/nanovna/NanoVNASaver/Hardware/Hardware.py", line 101, in get_VNA
    return NAME2DEVICE[iface.comment](iface)
  File "/home/ju/nanovna/NanoVNASaver/Hardware/NanoVNA.py", line 40, in __init__
    super().__init__(iface)
  File "/home/ju/nanovna/NanoVNASaver/Hardware/VNA.py", line 65, in __init__
    self.version = self.readVersion()
  File "/home/ju/nanovna/NanoVNASaver/Hardware/VNA.py", line 196, in readVersion
    result = list(self.exec_command("version"))
  File "/home/ju/nanovna/NanoVNASaver/Hardware/VNA.py", line 100, in exec_command
    line = line.decode("ascii").strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
Cancelled
NanoVNA-Saver version: [0.3.10-pre06]
And also all previous versions still available on Github.
System Debian bullseye python3.9
Notice:
On a friend's machine with Debian Buster and Python3.7 and NanoVNASaver0.3.8 my hardware is running.
I suspect a configuration error from me on the new computer. But where?

**Comment by ManfredII** [comment]
The issue no longer exists since update to the version 0.5.3 

![](https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png)
