### ISSUE TITLE
nanovna-saver-0.3.9: test failure: TypeError: VSWRAnalysis.__init__() missing 1 required positional argument: 'app'

### ISSUE THREAD

**Issue by yarda** [NanoVNA-Saver/nanovna-saver#443]
**Describe the bug**
`/usr/bin/python3 setup.py test` throws the following error:
```
Traceback (most recent call last):
  File "/builddir/build/BUILD/nanovna-saver-0.3.9/setup.py", line 34, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 159, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 223, in run
    self.run_tests()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 226, in run_tests
    test = unittest.main(
  File "/usr/lib64/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.10/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.10/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib64/python3.10/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.10/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.10/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib64/python3.10/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 56, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.10/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 56, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.10/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
TypeError: VSWRAnalysis.__init__() missing 1 required positional argument: 'app'
```

**To Reproduce**
Run `/usr/bin/python3 setup.py test`

**Expected behavior**
No traceback

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora Rawhide (AKA f36)
 - Python version: python-3.10
 - NanoVNA-Saver version: 0.3.9

**Additional context**

**Comment by zarath** [comment]
test are done in pipeline (pylint --exit-zero NanoVNASaver, pytest --cov=NanoVNASaver)
perhaps it will go in in future cleanups of setup structure and tools.
