### ISSUE TITLE
Crash when zooming or moving charts

### ISSUE THREAD

**Issue by khaytsus** [NanoVNA-Saver/nanovna-saver#525]
I used to be able to zoom in and move the charts around in the past, I haven't used my NanoVNA in a few months since analyzing all of my antennas so I don't know what has changed in the meanwhile but when I zoom and/or scroll in the charts after a few zooms or such it crashes 100% of the time.

**To Reproduce**
1. Load a sweep
2. Zoom into any of the charts of the sweep several times

**Expected behavior**
Zoom zoom, not zoom crash ;)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Fedora 35, x86_64
 - Python 3.10.5
 - NanoVNA-Saver version: 0.4.0

**Additional context**
NanoVNASaver 0.4.0                                                                        
                                                                                          
Copyright (C) 2019, 2020 Rune B. Broberg                                                  
Copyright (C) 2020ff NanoVNA-Saver Authors                                                
                                                                                          
This program comes with ABSOLUTELY NO WARRANTY                                            
This program is licensed under the GNU General Public License version 3                   
                                                                                          
See https://github.com/NanoVNA-Saver/nanovna-saver for further details.                   

Traceback (most recent call last):                                                        
  File "/usr/local/lib/python3.10/site-packages/NanoVNASaver/Charts/Frequency.py", line 447, in paintEvent
    self.drawValues(qp)                                                                   
  File "/usr/local/lib/python3.10/site-packages/NanoVNASaver/Charts/VSWR.py", line 144, in drawValues
    self.drawData(qp, self.data, Chart.color.sweep)                                                                                      
  File "/usr/local/lib/python3.10/site-packages/NanoVNASaver/Charts/Frequency.py", line 641, in drawData
    qp.drawLine(prevx, prevy, new_x, new_y)                         
TypeError: arguments did not match any overloaded call:                                                                                  
  drawLine(self, QLineF): argument 1 has unexpected type 'int'                                                                           
  drawLine(self, QLine): argument 1 has unexpected type 'int'                                                                            
  drawLine(self, int, int, int, int): argument 3 has unexpected type 'numpy.float64'                                                     
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'int'                                                                   
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'int'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPaintDevice: Cannot destroy paint device that is being painted                                                                          
Traceback (most recent call last):                                  
  File "/usr/local/lib/python3.10/site-packages/NanoVNASaver/Charts/Frequency.py", line 447, in paintEvent
    self.drawValues(qp)                                             
  File "/usr/local/lib/python3.10/site-packages/NanoVNASaver/Charts/VSWR.py", line 144, in drawValues
    self.drawData(qp, self.data, Chart.color.sweep)                                                                                      
  File "/usr/local/lib/python3.10/site-packages/NanoVNASaver/Charts/Frequency.py", line 641, in drawData
    qp.drawLine(prevx, prevy, new_x, new_y)                         
TypeError: arguments did not match any overloaded call:                                                                                  
  drawLine(self, QLineF): argument 1 has unexpected type 'int'                                                                           
  drawLine(self, QLine): argument 1 has unexpected type 'int'                                                                            
  drawLine(self, int, int, int, int): argument 3 has unexpected type 'numpy.float64'                                                     
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'int'                                                                   
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'int'
[1]    2206262 IOT instruction (core dumped)  NanoVNASaver

**Comment by khaytsus** [comment]
I am able to reproduce the same issue on both the release code from github and as well as the Fedora package.  I installed clean on my test laptop to make sure I didn't have some dirty environment from upgrades etc, and the crash is the same on the clean machine.
