### ISSUE TITLE
Crashing when connecting the device to Rpi

### ISSUE THREAD

**Issue by FilipCZE** [NanoVNA-Saver/nanovna-saver#555]
Using Rpi3 with RpiOS - Bullseye and NanoVNA V2_2 firmware version 20201013

1) Installation completed
2) Saver launched
3) After connecting to device - CRASH

Traceback (most recent call last):
  File "/home/Filip/.local/lib/python3.9/site-packages/NanoVNASaver/NanoVNASaver.py", line 517, in dataUpdated
    self.windows["tdr"].updateTDR()
  File "/home/Filip/.local/lib/python3.9/site-packages/NanoVNASaver/Windows/TDR.py", line 140, in updateTDR
    step_response = scipy.signal.convolve(self.td, step)
AttributeError: module 'scipy' has no attribute 'signal'

... How to get rid of:
libEGL warning: DRI2: failed to authenticate ?

NanoVNA-Saver version: 0.5.4-pre

**Comment by FilipCZE** [comment]
well thanks for advice, but I dont know what to do with this.

Im using NanoVNA V2_2 firmware version 20201013

**Comment by FilipCZE** [comment]
THANKS!

update of the TDR.py

install with pip3 install .

Run app -> Connect -> NO CRASH
