### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by oxoocoffee** [NanoVNA-Saver/nanovna-saver#583]
# Bug Report

**NanoVNA-Saver version:** 0.5.4 
MacOSX Ventura (Python 3.10.9)
nanoVNA-F V2 (firmware  v0.5.0)

**Current behavior:** Crash when applying calibration

**Expected behavior:** Apply Calibration

**Steps to reproduce:** 
1. Connect nanoVNA-F V2 (firmware  v0.5.0)
2. Start calibration (Short, Open, Load)
3. Press Apply when done
4. CRash

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
NanoVNASaver 0.5.4

Copyright (C) 2019, 2020 Rune B. Broberg
Copyright (C) 2020ff NanoVNA-Saver Authors

This program comes with ABSOLUTELY NO WARRANTY
This program is licensed under the GNU General Public License version 3

See https://github.com/NanoVNA-Saver/nanovna-saver for further details.

1   HIToolbox                           0x00007ff81d326726 _ZN15MenuBarInstance22EnsureAutoShowObserverEv + 102
2   HIToolbox                           0x00007ff81d3262b8 _ZN15MenuBarInstance14EnableAutoShowEv + 52
3   HIToolbox                           0x00007ff81d295cd7 _ZN15MenuBarInstance21UpdateAggregateUIModeE21MenuBarAnimationStylehhh + 1113
4   HIToolbox                           0x00007ff81d326173 _ZN15MenuBarInstance19SetFullScreenUIModeEjj + 175
5   AppKit                              0x00007ff8167ed4b7 -[NSApplication _setPresentationOptions:instance:flags:] + 1145
6   AppKit                              0x00007ff816642165 -[NSApplication _updateFullScreenPresentationOptionsForInstance:] + 582
7   CoreFoundation                      0x00007ff8134216d6 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
8   CoreFoundation                      0x00007ff8134bacbc ___CFXRegistrationPost_block_invoke + 86
9   CoreFoundation                      0x00007ff8134bac13 _CFXRegistrationPost + 534
10  CoreFoundation                      0x00007ff8133f4e31 _CFXNotificationPost + 809
11  Foundation                          0x00007ff814169f2c -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
12  AppKit                              0x00007ff8167edb28 spacesNotificationHandler + 119
13  SkyLight                            0x00007ff817f8b74d _ZN12_GLOBAL__N_123notify_datagram_handlerEj15CGSDatagramTypePvmS1_ + 1030
14  SkyLight                            0x00007ff81829e04a _ZN21CGSDatagramReadStream26dispatchMainQueueDatagramsEv + 202
15  SkyLight                            0x00007ff81829df71 ___ZN21CGSDatagramReadStream15mainQueueWakeupEv_block_invoke + 18
16  libdispatch.dylib                   0x00007ff8131d07fb _dispatch_call_block_and_release + 12
17  libdispatch.dylib                   0x00007ff8131d1a44 _dispatch_client_callout + 8
18  libdispatch.dylib                   0x00007ff8131de7b9 _dispatch_main_queue_drain + 952
19  libdispatch.dylib                   0x00007ff8131de3f3 _dispatch_main_queue_callback_4CF + 31
20  CoreFoundation                      0x00007ff81346a43d __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
21  CoreFoundation                      0x00007ff81342aecb __CFRunLoopRun + 2498
22  CoreFoundation                      0x00007ff813429e8f CFRunLoopRunSpecific + 560
23  HIToolbox                           0x00007ff81d2b3766 RunCurrentEventLoopInMode + 292
24  HIToolbox                           0x00007ff81d2b3396 ReceiveNextEventCommon + 199
25  HIToolbox                           0x00007ff81d2b32b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
26  AppKit                              0x00007ff8164b0f33 _DPSNextEvent + 909
27  AppKit                              0x00007ff8164afdb4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
28  AppKit                              0x00007ff8164a23f7 -[NSApplication run] + 586
29  libqcocoa.dylib                     0x0000000159db462f _ZN21QCocoaEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 2495
30  QtCore                              0x000000011beadacf _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
31  QtCore                              0x000000011beb2042 _ZN16QCoreApplication4execEv + 130
32  QtWidgets.abi3.so                   0x0000000117ff4de2 _ZL23meth_QApplication_exec_P7_objectS0_ + 82
33  Python                              0x00000001168dd9aa cfunction_call + 90
34  Python                              0x0000000116878841 _PyObject_MakeTpCall + 129
35  Python                              0x00000001169a65c7 _PyEval_EvalFrameDefault + 60471
36  Python                              0x000000011699664a PyEval_EvalCode + 282
37  nanovna-saver                       0x00000001049b73c4 nanovna-saver + 21444
38  nanovna-saver                       0x00000001049b78ac nanovna-saver + 22700
39  dyld                                0x00000002095a0310 start + 2432
1   HIToolbox                           0x00007ff81d2b30c2 _ZN15MenuBarInstance22RemoveAutoShowObserverEv + 30
2   HIToolbox                           0x00007ff81d2ef638 _ZL17BroadcastInternaljPvh + 167
3   SkyLight                            0x00007ff817f8b74d _ZN12_GLOBAL__N_123notify_datagram_handlerEj15CGSDatagramTypePvmS1_ + 1030
4   SkyLight                            0x00007ff81829e04a _ZN21CGSDatagramReadStream26dispatchMainQueueDatagramsEv + 202
5   SkyLight                            0x00007ff81829df71 ___ZN21CGSDatagramReadStream15mainQueueWakeupEv_block_invoke + 18
6   libdispatch.dylib                   0x00007ff8131d07fb _dispatch_call_block_and_release + 12
7   libdispatch.dylib                   0x00007ff8131d1a44 _dispatch_client_callout + 8
8   libdispatch.dylib                   0x00007ff8131de7b9 _dispatch_main_queue_drain + 952
9   libdispatch.dylib                   0x00007ff8131de3f3 _dispatch_main_queue_callback_4CF + 31
10  CoreFoundation                      0x00007ff81346a43d __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
11  CoreFoundation                      0x00007ff81342aecb __CFRunLoopRun + 2498
12  CoreFoundation                      0x00007ff813429e8f CFRunLoopRunSpecific + 560
13  HIToolbox                           0x00007ff81d2b3766 RunCurrentEventLoopInMode + 292
14  HIToolbox                           0x00007ff81d2b3576 ReceiveNextEventCommon + 679
15  HIToolbox                           0x00007ff81d2b32b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
16  AppKit                              0x00007ff8164b0f33 _DPSNextEvent + 909
17  AppKit                              0x00007ff8164afdb4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
18  AppKit                              0x00007ff8164a23f7 -[NSApplication run] + 586
19  libqcocoa.dylib                     0x0000000159db462f _ZN21QCocoaEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 2495
20  QtCore                              0x000000011beadacf _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
21  QtCore                              0x000000011beb2042 _ZN16QCoreApplication4execEv + 130
22  QtWidgets.abi3.so                   0x0000000117ff4de2 _ZL23meth_QApplication_exec_P7_objectS0_ + 82
23  Python                              0x00000001168dd9aa cfunction_call + 90
24  Python                              0x0000000116878841 _PyObject_MakeTpCall + 129
25  Python                              0x00000001169a65c7 _PyEval_EvalFrameDefault + 60471
26  Python                              0x000000011699664a PyEval_EvalCode + 282
27  nanovna-saver                       0x00000001049b73c4 nanovna-saver + 21444
28  nanovna-saver                       0x00000001049b78ac nanovna-saver + 22700
29  dyld                                0x00000002095a0310 start + 2432
1   HIToolbox                           0x00007ff81d326726 _ZN15MenuBarInstance22EnsureAutoShowObserverEv + 102
2   HIToolbox                           0x00007ff81d295ce3 _ZN15MenuBarInstance21UpdateAggregateUIModeE21MenuBarAnimationStylehhh + 1125
3   HIToolbox                           0x00007ff81d326173 _ZN15MenuBarInstance19SetFullScreenUIModeEjj + 175
4   AppKit                              0x00007ff8167ed4b7 -[NSApplication _setPresentationOptions:instance:flags:] + 1145
5   AppKit                              0x00007ff816642165 -[NSApplication _updateFullScreenPresentationOptionsForInstance:] + 582
6   CoreFoundation                      0x00007ff8134216d6 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
7   CoreFoundation                      0x00007ff8134bacbc ___CFXRegistrationPost_block_invoke + 86
8   CoreFoundation                      0x00007ff8134bac13 _CFXRegistrationPost + 534
9   CoreFoundation                      0x00007ff8133f4e31 _CFXNotificationPost + 809
10  Foundation                          0x00007ff814169f2c -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
11  AppKit                              0x00007ff8167edb28 spacesNotificationHandler + 119
12  SkyLight                            0x00007ff817f8b74d _ZN12_GLOBAL__N_123notify_datagram_handlerEj15CGSDatagramTypePvmS1_ + 1030
13  SkyLight                            0x00007ff81829e04a _ZN21CGSDatagramReadStream26dispatchMainQueueDatagramsEv + 202
14  SkyLight                            0x00007ff81829df71 ___ZN21CGSDatagramReadStream15mainQueueWakeupEv_block_invoke + 18
15  libdispatch.dylib                   0x00007ff8131d07fb _dispatch_call_block_and_release + 12
16  libdispatch.dylib                   0x00007ff8131d1a44 _dispatch_client_callout + 8
17  libdispatch.dylib                   0x00007ff8131de7b9 _dispatch_main_queue_drain + 952
18  libdispatch.dylib                   0x00007ff8131de3f3 _dispatch_main_queue_callback_4CF + 31
19  CoreFoundation                      0x00007ff81346a43d __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
20  CoreFoundation                      0x00007ff81342aecb __CFRunLoopRun + 2498
21  CoreFoundation                      0x00007ff813429e8f CFRunLoopRunSpecific + 560
22  HIToolbox                           0x00007ff81d2b3766 RunCurrentEventLoopInMode + 292
23  HIToolbox                           0x00007ff81d2b3576 ReceiveNextEventCommon + 679
24  HIToolbox                           0x00007ff81d2b32b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
25  AppKit                              0x00007ff8164b0f33 _DPSNextEvent + 909
26  AppKit                              0x00007ff8164afdb4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
27  AppKit                              0x00007ff8164a23f7 -[NSApplication run] + 586
28  libqcocoa.dylib                     0x0000000159db462f _ZN21QCocoaEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 2495
29  QtCore                              0x000000011beadacf _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
30  QtCore                              0x000000011beb2042 _ZN16QCoreApplication4execEv + 130
31  QtWidgets.abi3.so                   0x0000000117ff4de2 _ZL23meth_QApplication_exec_P7_objectS0_ + 82
32  Python                              0x00000001168dd9aa cfunction_call + 90
33  Python                              0x0000000116878841 _PyObject_MakeTpCall + 129
34  Python                              0x00000001169a65c7 _PyEval_EvalFrameDefault + 60471
35  Python                              0x000000011699664a PyEval_EvalCode + 282
36  nanovna-saver                       0x00000001049b73c4 nanovna-saver + 21444
37  nanovna-saver                       0x00000001049b78ac nanovna-saver + 22700
38  dyld                                0x00000002095a0310 start + 2432
2023-01-14 10:41:51,126 - NanoVNASaver.Calibration - WARNING - Tried to calibrate from insufficient data.
Traceback (most recent call last):
  File "NanoVNASaver/Windows/CalibrationSettings.py", line 793, in automaticCalibrationStep
  File "NanoVNASaver/Windows/CalibrationSettings.py", line 565, in calculate
  File "NanoVNASaver/Calibration.py", line 256, in calc_corrections
ValueError: All of short, open and load calibration stepsmust be completed for calibration to be applied.
```
![Calibration](https://user-images.githubusercontent.com/2259575/212484705-bfeca965-2ce2-4c48-95bb-7d6ee5bfbf5b.jpg)

**Comment by pgramsey** [comment]
I get a lot of crashes on calibration, too. Win 11. V 0.5.4.

Sometimes it works. Sometimes it crashes when calibration is complete and I it "apply". Sometimes it crashes at the completion of the first calibration step.
