### ISSUE TITLE
Crash trying to sweep

### ISSUE THREAD

**Issue by oxoocoffee** [NanoVNA-Saver/nanovna-saver#584]
# Bug Report

**NanoVNA-Saver version:**0.5.4
MacOSX Ventura (Python 3.10.9)
nanoVNA-F V2 (firmware v0.5.0)

**Current behavior:** Crash trying to sweep

**Expected behavior:**

**Steps to reproduce:**
1. Use VNA builtin calibration (Short, Open, Load)
2. Connect nanoVNA-F V2 (firmware v0.5.0)
3. Change segments from 1 to 10
4. Scan
5. CRash

**Related code:**

```
insert short code snippets here
```

**Other information:**

Same screenshot as https://github.com/NanoVNA-Saver/nanovna-saver/issues/583 

List of pip installed
```
MBP ➜   pip list
Package            Version
------------------ -----------
beautifulsoup4     4.11.1
bs4                0.0.1
certifi            2022.12.7
charset-normalizer 2.1.1
commonmark         0.9.1
idna               3.4
numpy              1.24.1
packaging          23.0
pcapdump           0.0.0
pip                22.3.1
pip-review         1.3.0
pip-search         0.0.12
protobuf           4.21.12
Pygments           2.14.0
pyqtgraph          0.13.1
requests           2.28.1
rich               13.0.1
setuptools         65.6.3
soupsieve          2.3.2.post1
urllib3            1.26.13
wheel              0.38.4
```

```
NanoVNASaver 0.5.4

Copyright (C) 2019, 2020 Rune B. Broberg
Copyright (C) 2020ff NanoVNA-Saver Authors

This program comes with ABSOLUTELY NO WARRANTY
This program is licensed under the GNU General Public License version 3

See https://github.com/NanoVNA-Saver/nanovna-saver for further details.

1   HIToolbox                           0x00007ff81d326726 _ZN15MenuBarInstance22EnsureAutoShowObserverEv + 102
2   HIToolbox                           0x00007ff81d3262b8 _ZN15MenuBarInstance14EnableAutoShowEv + 52
3   HIToolbox                           0x00007ff81d295cd7 _ZN15MenuBarInstance21UpdateAggregateUIModeE21MenuBarAnimationStylehhh + 1113
4   HIToolbox                           0x00007ff81d326173 _ZN15MenuBarInstance19SetFullScreenUIModeEjj + 175
5   AppKit                              0x00007ff8167ed4b7 -[NSApplication _setPresentationOptions:instance:flags:] + 1145
6   AppKit                              0x00007ff816642165 -[NSApplication _updateFullScreenPresentationOptionsForInstance:] + 582
7   CoreFoundation                      0x00007ff8134216d6 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
8   CoreFoundation                      0x00007ff8134bacbc ___CFXRegistrationPost_block_invoke + 86
9   CoreFoundation                      0x00007ff8134bac13 _CFXRegistrationPost + 534
10  CoreFoundation                      0x00007ff8133f4e31 _CFXNotificationPost + 809
11  Foundation                          0x00007ff814169f2c -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
12  AppKit                              0x00007ff8167edb28 spacesNotificationHandler + 119
13  SkyLight                            0x00007ff817f8b74d _ZN12_GLOBAL__N_123notify_datagram_handlerEj15CGSDatagramTypePvmS1_ + 1030
14  SkyLight                            0x00007ff81829e04a _ZN21CGSDatagramReadStream26dispatchMainQueueDatagramsEv + 202
15  SkyLight                            0x00007ff81829df71 ___ZN21CGSDatagramReadStream15mainQueueWakeupEv_block_invoke + 18
16  libdispatch.dylib                   0x00007ff8131d07fb _dispatch_call_block_and_release + 12
17  libdispatch.dylib                   0x00007ff8131d1a44 _dispatch_client_callout + 8
18  libdispatch.dylib                   0x00007ff8131de7b9 _dispatch_main_queue_drain + 952
19  libdispatch.dylib                   0x00007ff8131de3f3 _dispatch_main_queue_callback_4CF + 31
20  CoreFoundation                      0x00007ff81346a43d __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
21  CoreFoundation                      0x00007ff81342aecb __CFRunLoopRun + 2498
22  CoreFoundation                      0x00007ff813429e8f CFRunLoopRunSpecific + 560
23  HIToolbox                           0x00007ff81d2b3766 RunCurrentEventLoopInMode + 292
24  HIToolbox                           0x00007ff81d2b3576 ReceiveNextEventCommon + 679
25  HIToolbox                           0x00007ff81d2b32b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
26  AppKit                              0x00007ff8164b0f33 _DPSNextEvent + 909
27  AppKit                              0x00007ff8164afdb4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
28  AppKit                              0x00007ff8164a23f7 -[NSApplication run] + 586
29  libqcocoa.dylib                     0x000000015811d62f _ZN21QCocoaEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 2495
30  QtCore                              0x000000011a216acf _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
31  QtCore                              0x000000011a21b042 _ZN16QCoreApplication4execEv + 130
32  QtWidgets.abi3.so                   0x000000011635dde2 _ZL23meth_QApplication_exec_P7_objectS0_ + 82
33  Python                              0x0000000114c469aa cfunction_call + 90
34  Python                              0x0000000114be1841 _PyObject_MakeTpCall + 129
35  Python                              0x0000000114d0f5c7 _PyEval_EvalFrameDefault + 60471
36  Python                              0x0000000114cff64a PyEval_EvalCode + 282
37  nanovna-saver                       0x0000000102d203c4 nanovna-saver + 21444
38  nanovna-saver                       0x0000000102d208ac nanovna-saver + 22700
39  dyld                                0x0000000207679310 start + 2432
2023-01-14 10:56:01,457 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.315533 -13.111677)
2023-01-14 10:56:01,935 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.315533 -13.111677)
2023-01-14 10:56:02,804 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.217932 -13.152149)
2023-01-14 10:56:03,285 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.217932 -13.152149)
2023-01-14 10:56:04,141 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.278017 -13.069251)
2023-01-14 10:56:04,347 - NanoVNASaver.SweepWorker - ERROR - Tried and failed to read data 1 5 times.
2023-01-14 10:56:04,740 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.278017 -13.069251)
2023-01-14 10:56:05,489 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.155504 -13.167605)
2023-01-14 10:56:05,971 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.155504 -13.167605)
2023-01-14 10:56:06,835 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.204075 -13.108471)
2023-01-14 10:56:07,321 - NanoVNASaver.SweepWorker - WARNING - Got a non plausible data value: (-19.204075 -13.108471)
2023-01-14 10:56:07,527 - NanoVNASaver.SweepWorker - CRITICAL - Tried and failed to read data 1 10 times. Giving up.
2023-01-14 10:56:07,528 - NanoVNASaver.SweepWorker - ERROR - Failed reading data 1 10 times.
Data outside expected valid ranges, or in an unexpected format.

You can disable data validation on thedevice settings screen.
Traceback (most recent call last):
  File "NanoVNASaver/SweepWorker.py", line 79, in run
  File "NanoVNASaver/SweepWorker.py", line 104, in _run
  File "NanoVNASaver/SweepWorker.py", line 133, in _run_loop
  File "NanoVNASaver/SweepWorker.py", line 228, in readAveragedSegment
  File "NanoVNASaver/SweepWorker.py", line 261, in readSegment
  File "NanoVNASaver/SweepWorker.py", line 305, in readData
OSError: Failed reading data 1 10 times.
Data outside expected valid ranges, or in an unexpected format.

You can disable data validation on thedevice settings screen.
Traceback (most recent call last):
  File "NanoVNASaver/SweepWorker.py", line 84, in run
  File "NanoVNASaver/SweepWorker.py", line 79, in run
  File "NanoVNASaver/SweepWorker.py", line 104, in _run
  File "NanoVNASaver/SweepWorker.py", line 133, in _run_loop
  File "NanoVNASaver/SweepWorker.py", line 228, in readAveragedSegment
  File "NanoVNASaver/SweepWorker.py", line 261, in readSegment
  File "NanoVNASaver/SweepWorker.py", line 305, in readData
OSError: Failed reading data 1 10 times.
Data outside expected valid ranges, or in an unexpected format.

You can disable data validation on thedevice settings screen.

Saving session...completed.
```

**Comment by oxoocoffee** [comment]
I did try to switch to 0.5.3 and on sweep with out making any configuration changes I get this dialog box. Looks like 0.5.4 crash stack also has this error but it never shows up

<img width="220" alt="0 5 3" src="https://user-images.githubusercontent.com/2259575/212486668-e027b69c-65c1-41eb-93d1-c2a5f800cb78.png">
