### ISSUE TITLE
bug: ModuleNotFoundError: No module named 'setuptools_scm'

### ISSUE THREAD

**Issue by zodoczi** [NanoVNA-Saver/nanovna-saver#694]
version 0.6.3
windows 10, python

PS C:\utils\nanovna_063\nanovna-saver> py nanovna-saver.py
Traceback (most recent call last):
  File "C:\utils\nanovna_063\nanovna-saver\nanovna-saver.py", line 32, in <module>
    import NanoVNASaver.__main__
  File "C:\utils\nanovna_063\nanovna-saver\src\NanoVNASaver\__main__.py", line 33, in <module>
    from NanoVNASaver.About import version, INFO
  File "C:\utils\nanovna_063\nanovna-saver\src\NanoVNASaver\About.py", line 20, in <module>
    from setuptools_scm import get_version
ModuleNotFoundError: No module named 'setuptools_scm'

**Comment by PA2ER** [comment]
Same her on Fedora 40 Plasma. NanoVNASaver V0.6.3 and the new v0.6.4.

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/NanoVNASaver/About.py", line 22, in <module>
    version = get_version(root='..', relative_to=__file__)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools_scm/_get_version_impl.py", line 158, in get_version
    _version_missing(config)
  File "/usr/lib/python3.12/site-packages/setuptools_scm/_get_version_impl.py", line 112, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /usr/lib/python3.12/site-packages.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/NanoVNASaver", line 33, in <module>
    sys.exit(load_entry_point('NanoVNASaver==0.6.4', 'console_scripts', 'NanoVNASaver')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/NanoVNASaver", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/NanoVNASaver/__main__.py", line 33, in <module>
    from NanoVNASaver.About import version, INFO
  File "/usr/lib/python3.12/site-packages/NanoVNASaver/About.py", line 24, in <module>
    from NanoVNASaver._version import version
ModuleNotFoundError: No module named 'NanoVNASaver._version'
