### ISSUE TITLE
bug: Crashes after calirbating single port manually

### ISSUE THREAD

**Issue by hansen-mc** [NanoVNA-Saver/nanovna-saver#699]
# Bug Report

**NanoVNA-Saver version:** [a04d6d9], v0.6.3 also 

**Current behavior:**
System: Windows 10, 64bit, running the python code

when calibrating a single port (short, open, load) software crashes with clicking on "apply"

```
2024-05-15 12:40:32,202 - NanoVNASaver.Calibration - ERROR - Division error - did you use the same measurement for two of short, open and load?
Traceback (most recent call last):
  File "c:\DEV\TOOLS\nanovna-saver-main\src\NanoVNASaver\Calibration.py", line 352, in calc_corrections
    self._calc_port_1(freq, caldata)
  File "c:\DEV\TOOLS\nanovna-saver-main\src\NanoVNASaver\Calibration.py", line 310, in _calc_port_1
    -(
ZeroDivisionError: complex division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\DEV\TOOLS\nanovna-saver-main\src\NanoVNASaver\Windows\CalibrationSettings.py", line 605, in calculate
    self.app.calibration.calc_corrections()
  File "c:\DEV\TOOLS\nanovna-saver-main\src\NanoVNASaver\Calibration.py", line 361, in calc_corrections
    raise ValueError(
ValueError: Two of short, open and load returned the same values at frequency 9000Hz.
```

while, when using the assisint, the Saver works just fine.

**Expected behavior:**

running through a single port calibration should not only with the assistent. 

**Steps to reproduce:**

Running the calibration each time without the assitent

**Other information:**

maybe you could seperate "short" "open" and "load" buttons for each port

**Comment by pionalbl** [comment]
This appears to be related to having the S11 Serial C display open.  I have the following display grid:
Upper Left: S11 Smith Chart
Upper Right: S11 Return Loss
Lower Left: S11 R+jX
Lower Right: S11 Serial C

With this configuration it crashes regularly.  If I close the S11 Serial C window I don't seem to have the crash.
