### ISSUE TITLE
Reported Bug in Windows Binaries conflicting with latest DisLord Firmware for NanoVNA-D and NanoVNA-H

### ISSUE THREAD

**Issue by Ghaz75** [NanoVNA-Saver/nanovna-saver#708]
I had an old firmware loaded in my NanoVNA-H and I used this new release of your Software and it was working fine. Then I installed DFUSeDemo and its corresponding STM32080 driver to upgrade the firmware of my NanoVNA-H. I used DisLord NanoVNA.H.v1.2.29.dfu for upgrade.
Since then following error is generated once I run this version of your software or any previous version of it from both x86 and x64 binaries. However the device with the above mentioned new firmware works fine with other softwares like NanoVNA-App by OneofEleven and VNASharp etc. Your app gives same error now whether device is connected or not, right at the start and does not load. 

Traceback (most recent call last):
  File "nanovna-saver.py", line 37, in <module>
  File "NanoVNASaver\__main__.py", line 95, in main
  File "NanoVNASaver\NanoVNASaver.py", line 128, in __init__
  File "NanoVNASaver\Controls\MarkerControl.py", line 46, in __init__
  File "NanoVNASaver\Marker\Widget.py", line 163, in __init__
  File "NanoVNASaver\Marker\Widget.py", line 206, in buildForm
TypeError: object of type 'NoneType' has no len()

It may be possible that DFU app and its driver have conflict with your python based windows binaries.

**Comment by zarath** [comment]
No information about Version. No fix...
